# Add yarn binaries to PATH
export PATH=$PATH:/home/damejia/.yarn/bin

# Add Go 1.10 to Path
export PATH=$PATH:/usr/local/go/bin

# Add GOPATH for GO language
export GOPATH=/home/damejia/Repositories

# Add Go bin path (created in the GOPATH/bin by GO
# This will allow me to run the binaries in $GOPATH/bin like `excercism`
# go_bin selects the first directory in the $GOPATH
go_bin=$(echo $GOPATH | awk -F":" '{print $1}')
export PATH=$PATH:$go_bin/bin

# Add custom scripts
export PATH=$PATH:/home/damejia/bin

# Add Rust bin
export PATH=$PATH:/home/damejia/.cargo/bin

# Add MongoDB here
export PATH=$PATH:/home/damejia/opt/mongodb_3.6.5/bin

# Source CERN-ROOT data analysis framework
# This enables root notebooks in jupyter
#source /home/damejia/opt/root/root7_build/bin/thisroot.sh

# ESP32 Toolchain
export IDF_PATH=/home/damejia/opt/esp/esp-idf
export PATH=$PATH:$HOME/opt/esp/xtensa-esp32-elf/bin

# Parallelo Go PATHs
# Sets the gopath for parallelo
set_go_path_parallelo(){
  export GOPATH="/home/damejia/Repositories/src/bitbucket.org/Daniel-M/PARALLELO.AI/Go"
  echo "Go path set to '$GOPATH'"
}

# history + grep
# grepstory word looks for "word" in the bash history
grepstory() {
  usage(){
    echo "Usage: grepstory word"
  } # define is_file_exits function
 
 # call usage() function if filename not supplied
	if [[ ! $1 -eq 0 ]]
	then
		history | grep $1
	else
		usage
	fi
}

# neovim open
# nvimopen ext opens all .ext files under the tree
nvimopen(){
  usage(){
    echo "Usage: nvimopen file extension without dot"
  } # define is_file_exits function

  # call usage() function if filename not supplied
	if [[ ! $1 -eq 0 ]]
	then
		nvim $(find -type f -name "*.$1" | awk 'BEGIN{text=""}{text=text" "$1} END{print text}')
	else
		usage
	fi	
}

xc_file_contents(){
  #!/bin/bash
  # file.sh: a sample shell script to demonstrate the concept of Bash shell functions
  # define usage function
  usage(){
    echo "Usage: xc_file_contents filename"
  } # define is_file_exits function
  # $f -> store argument passed to the script
  is_file_exits(){
    local f="$1"
    [[ -f "$f" ]] && return 0 || return 1
  }
  # invoke usage
  # call usage() function if filename not supplied
  [[ $# -eq 0 ]] && usage # Invoke is_file_exits
  if ( is_file_exits "$1" )
  then
		cat $1 | xclip -sel clip
    cat $1 | xclip -sel primary 
    echo "Contents of file '$1' copied to clipboard"
  else
    echo "File $1 not found"
  fi
}

xc_readlink(){
	#!/bin/bash
	# file.sh: a sample shell script to demonstrate the concept of Bash shell functions
	# define usage function
	usage(){
		echo "Usage: xc_readlink filename"
	} # define is_file_exits function
	# $f -> store argument passed to the script
	is_file_exits(){
		local f="$1"
		[[ -f "$f" ]] && return 0 || return 1
	}
	# invoke usage
	# call usage() function if filename not supplied
	[[ $# -eq 0 ]] && usage # Invoke is_file_exits
	if ( is_file_exits "$1" )
	then
		route=$(readlink -f $1)
		echo -n $route | xclip -sel clip
		echo -n $route | xclip -sel primary 
		echo "Route to the file '$1' copied to clipboard"
	else
		echo "File $1 not found"
	fi
}

## Show git branch in prompt
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[31m\]\$(parse_git_branch)\[\033[00m\]\$ "

# Adding handy aliases
alias rm='rm -vi'

alias cp='cp -vi'
alias mv='mv -vi'

alias ls='ls -h --color=auto'
alias ll='ls -l --color=auto'
alias la='ll -a --color=auto'

# Environment aliases
alias bitbucket='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M'
alias github='cd /home/damejia/Repositories//src/github.com/Daniel-M'
alias ddropbox='cd /home/damejia/Dropbox'
alias ddescargas='cd /home/damejia/Descargas'

alias Dualmonright='xrandr --output LVDS --auto --rotate normal --pos 0x0 --output CRT1 --auto --right-of LVDS'
alias Dualmonleft='xrandr --output LVDS --auto --rotate normal --pos 0x0 --output CRT1 --auto --left-of LVDS'
alias ColoredTerminal='export TERM=xterm-256color'

alias gfif-cluster='ssh -X biofisica_user1@gfif.udea.edu.co'
alias itm-cluster='ssh -X biofisicaudea@190.248.28.132'

alias MongoIB='mongo -u admin -p xudmaster5. --authenticationDatabase admin'
alias MongoBB='mongo --port 37017 -u admin -p papa123$. --authenticationDatabase admin --host 181.143.87.202'

alias xc-pwd='pwd | xclip -sel clip'

# Volatile aliases

alias BStochastic="mupdf '/home/damejia/Books/Libros_y_Articulos_Regados/pdf/(Springer Series in Synergetics) Péter Érdi, Gábor Lente (auth.)-Stochastic Chemical Kinetics_ Theory and (Mostly) Systems Biological Applications-Springer New York (2014).pdf'"

alias BOksendal="mupdf '/home/damejia/Biophysics_Research/Undergraduate_Thesis/2-Bibliography/Oksendal_B._-_Stochastic_Differential_Equations_(5th_ed.).pdf'"

alias EquliPert='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M/EquilibriumPerturbationReversibleReaction'

alias Parallelo='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M/PARALLELO.AI'
