# Add GOPATH for GO language
export GOPATH=/home/damejia/Repositories

# Add Go bin path (created in the GOPATH/bin by GO
# This will allow me to run the binaries in $GOPATH/bin like `excercism`
# go_bin selects the first directory in the $GOPATH
go_bin=$(echo $GOPATH | awk -F":" '{print $1}')
export PATH=$PATH:$go_bin/bin

# Add custom scripts
export PATH=$PATH:/home/damejia/bin

# Add Rust bin
export PATH=$PATH:/home/damejia/.cargo/bin

# Source CERN-ROOT data analysis framework
# This enables root notebooks in jupyter
source /home/damejia/opt/root/root7_build/bin/thisroot.sh

# Adding handy aliases
alias rm='rm -vi'

alias cp='cp -vi'
alias mv='mv -vi'

alias ls='ls -h --color=auto'
alias ll='ls -l --color=auto'
alias la='ll -a --color=auto'

# Environment aliases
alias bitbucket='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M'
alias github='cd /home/damejia/Repositories//src/github.com/Daniel-M'
alias ddropbox='cd /home/damejia/Dropbox'
alias ddacademicos='cd /home/damejia/Academicos'
alias ddescargas='cd /home/damejia/Descargas'
alias Uundergrad='cd /home/damejia/Dropbox/1-Research/1-Undergrad_Thesis/5-Writting'

alias Dualmonright='xrandr --output LVDS --auto --rotate normal --pos 0x0 --output CRT1 --auto --right-of LVDS'
alias Dualmonleft='xrandr --output LVDS --auto --rotate normal --pos 0x0 --output CRT1 --auto --left-of LVDS'
alias ColoredTerminal='export TERM=xterm-256color'

alias gfif-cluster='ssh -X biofisica_user1@gfif.udea.edu.co'
alias itm-cluster='ssh -X biofisicaudea@190.248.28.132'

# Volatile aliases

alias BStochastic="mupdf '/home/damejia/Descargas/Libros_y_Articulos_Regados/(Springer Series in Synergetics) Péter Érdi, Gábor Lente (auth.)-Stochastic Chemical Kinetics_ Theory and (Mostly) Systems Biological Applications-Springer New York (2014).pdf'"

alias BOksendal="mupdf '/home/damejia/Biophysics_Research/Undergraduate_Thesis/2-Bibliography/Oksendal_B._-_Stochastic_Differential_Equations_(5th_ed.).pdf'"

alias CaPaper='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M/MathAspectsCaMuskin/'
alias EquliPert='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M/EquilibriumPerturbationReversibleReaction'

alias WorkProjects='cd /home/damejia/Repositories/src/bitbucket.org/Daniel-M/analysis-algorithms'
alias Parallelo='cd /home/damejia/Dropbox/Parallelo.ai'
